// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiLyPhBbT1y4A7NSRTUsBRCcDridK4dI',
    appId: '1:156314384206:web:14b4eadc5f06e85275101f',
    messagingSenderId: '156314384206',
    projectId: 'mobiliti-b',
    authDomain: 'mobiliti-b.firebaseapp.com',
    storageBucket: 'mobiliti-b.firebasestorage.app',
    measurementId: 'G-VYGCFKK81K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZLTjiW_dFBos8sxWVp7bqEp3HBBrr2ao',
    appId: '1:156314384206:android:08742d992bf5d7fe75101f',
    messagingSenderId: '156314384206',
    projectId: 'mobiliti-b',
    storageBucket: 'mobiliti-b.firebasestorage.app',
  );
}
